version: '3.8'

services:
  app:
    image: thread-benchmark
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_started
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=Benchmark


  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: